name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install

      - name: Run tests
        run: poetry run pytest
        
      - name: Run type checks
        run: poetry run mypy src

      - name: Run style checks
        run: |
          poetry run black --check src
          poetry run flake8 src
